function escapeHtml(value) {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}

function formatDate(value) {
  if (!value) return 'Not recorded';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return String(value);
  return date.toLocaleString();
}

export function receiptFileName(receipt) {
  const datePart = new Date(receipt?.cast_at ?? Date.now()).toISOString().slice(0, 10);
  return `secure-vote-receipt-${datePart}.html`;
}

export function receiptHtml(receipt) {
  const electionTitle = escapeHtml(receipt?.election_title ?? receipt?.election_name ?? 'Election');
  const receiptHash = escapeHtml(receipt?.receipt_hash ?? '');
  const blockHash = escapeHtml(receipt?.current_block_hash ?? receipt?.receipt_hash ?? '');
  const blockIndex = escapeHtml(receipt?.block_index ?? 'Pending');
  const chainStatus = escapeHtml(receipt?.chain_status ?? 'valid_live_chain');
  const castAt = escapeHtml(formatDate(receipt?.cast_at));

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Secure Vote Receipt</title>
  <style>
    :root { color-scheme: light; --green:#007a55; --green2:#159447; --ink:#102033; --muted:#5d6b7b; --line:#c9ded7; }
    * { box-sizing: border-box; }
    body { margin:0; min-height:100vh; display:grid; place-items:center; padding:28px; font-family: Inter, "Hind Siliguri", "Segoe UI", Arial, sans-serif; color:var(--ink); background:linear-gradient(135deg,#e8fbf6 0%,#f6f8ff 48%,#fff0f8 100%); }
    .receipt { width:min(820px,100%); overflow:hidden; border:1px solid rgba(0,122,85,.18); border-radius:24px; background:rgba(255,255,255,.92); box-shadow:0 30px 80px rgba(13,31,51,.16); }
    .top { padding:34px; color:white; background:radial-gradient(circle at top right,rgba(255,255,255,.28),transparent 32%),linear-gradient(135deg,var(--green),var(--green2)); }
    .eyebrow { margin:0 0 8px; font-size:13px; font-weight:800; letter-spacing:.12em; text-transform:uppercase; opacity:.86; }
    h1 { margin:0; font-size:34px; line-height:1.08; }
    .body { padding:30px 34px 34px; }
    .grid { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:16px; }
    .box { border:1px solid var(--line); border-radius:18px; padding:18px; background:linear-gradient(180deg,#fff,rgba(237,250,246,.72)); }
    .label { margin:0 0 7px; color:var(--muted); font-size:13px; font-weight:800; text-transform:uppercase; }
    .value { margin:0; font-size:19px; font-weight:800; overflow-wrap:anywhere; }
    .hash { grid-column:1/-1; }
    .hash .value { font-family:"Cascadia Mono","Consolas",monospace; font-size:15px; line-height:1.55; }
    .note { margin:22px 0 0; padding:16px 18px; border-radius:16px; color:#075c43; background:#e8f8f1; font-weight:700; }
    .footer { margin-top:20px; color:var(--muted); font-size:13px; line-height:1.7; }
    @media print { body { background:white; padding:0; } .receipt { box-shadow:none; border-radius:0; } }
    @media (max-width:640px) { body { padding:14px; } .top,.body { padding:22px; } h1 { font-size:26px; } .grid { grid-template-columns:1fr; } }
  </style>
</head>
<body>
  <main class="receipt">
    <section class="top">
      <p class="eyebrow">Secure Digital Voting Receipt</p>
      <h1>Anonymous Ballot Inclusion Proof</h1>
    </section>
    <section class="body">
      <div class="grid">
        <div class="box"><p class="label">Election</p><p class="value">${electionTitle}</p></div>
        <div class="box"><p class="label">Cast Time</p><p class="value">${castAt}</p></div>
        <div class="box"><p class="label">Block Index</p><p class="value">${blockIndex}</p></div>
        <div class="box"><p class="label">Chain Status</p><p class="value">${chainStatus}</p></div>
        <div class="box hash"><p class="label">Receipt Hash</p><p class="value">${receiptHash}</p></div>
        <div class="box hash"><p class="label">Current Block Hash</p><p class="value">${blockHash}</p></div>
      </div>
      <p class="note">This receipt can verify that a ballot is included in the public ledger without exposing voter identity or selected candidate.</p>
      <p class="footer">Generated by Secure Digital Voting System. Keep the receipt hash private if you do not want others to verify your participation.</p>
    </section>
  </main>
</body>
</html>`;
}

export function downloadVoteReceipt(receipt) {
  const blob = new Blob([receiptHtml(receipt)], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = receiptFileName(receipt);
  link.click();
  URL.revokeObjectURL(url);
}
