import { createContext, useEffect, useMemo, useState } from 'react';

const translations = {
  en: {
    home: 'Home',
    elections: 'Elections',
    howItWorks: 'How It Works',
    security: 'Security',
    voteVerification: 'Vote Verification',
    help: 'Help',
    login: 'Login',
    voterLogin: 'Voter Login',
    adminLogin: 'Admin Login',
    register: 'Register',
    projectTitle: 'Blockchain-Based Secure Digital Voting System',
    heroSubtitle: 'A university Web Engineering Lab project for secure voter registration, verified login, anonymous ballots, blockchain-style vote storage, and live election analytics.',
    viewElections: 'View Elections',
    howVotingWorks: 'How Voting Works',
    liveElectionHub: 'Live Election Hub',
    liveElectionDescription: 'Currently running elections, vote counts, leading candidates, timing, turnout, and seat-wise progress.',
    runningNow: 'Running now',
    totalVotes: 'Total votes',
    leading: 'Leading',
    timeLeft: 'Time left',
    seat: 'Seat',
    liveChart: 'Live chart',
    coreFeatures: 'Core Features',
    coreFeaturesDescription: 'Simple, secure, and verifiable features for a lab demonstration.',
    votingProcess: 'Voting Process',
    importantNotice: 'Important Notice',
    noticeText: 'This is an academic project. It is not suitable for real government elections without certified identity verification, formal security audits, legal approval, and independent infrastructure review.',
    securityAssurance: 'Security Assurance',
    securityAssuranceText: 'Ballots do not store name, email, phone, or NID directly. Vote blocks use SHA-256 hashes and previous block references so tampering can be detected during audit verification.',
    voterRegistration: 'Voter Registration',
    registrationDescription: 'Create one secure voter account using email, phone, and an approved 10 or 16 digit voter/NID number.',
    visitorMessage: 'Visitors can read the public project pages directly. Voters and admins must sign in for protected actions.',
    emailAddress: 'Email address',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    createVoterAccount: 'Create voter account',
    adminLoginOption: 'Admin login option',
    securityMessage: 'Security message',
    approvalWarning: 'Accounts waiting for approval or suspended by admin cannot vote even after login.',
    account: 'Account',
    voterInformation: 'Voter Information',
    review: 'Review',
    fullName: 'Full name',
    confirmPassword: 'Confirm password',
    voterNidNumber: 'Voter/NID number',
    dateOfBirth: 'Date of birth',
    phoneNumber: 'Phone number',
    region: 'Region',
    back: 'Back',
    continue: 'Continue',
    submitRegistration: 'Submit registration',
  },
  bn: {
    home: 'হোম',
    elections: 'নির্বাচন',
    howItWorks: 'কিভাবে কাজ করে',
    security: 'নিরাপত্তা',
    voteVerification: 'ভোট যাচাই',
    help: 'সহায়তা',
    login: 'লগইন',
    voterLogin: 'ভোটার লগইন',
    adminLogin: 'অ্যাডমিন লগইন',
    register: 'রেজিস্ট্রেশন',
    projectTitle: 'ব্লকচেইন-ভিত্তিক নিরাপদ ডিজিটাল ভোটিং সিস্টেম',
    heroSubtitle: 'নিরাপদ ভোটার নিবন্ধন, যাচাইকৃত লগইন, গোপন ব্যালট, ব্লকচেইন-স্টাইল ভোট সংরক্ষণ এবং লাইভ নির্বাচন বিশ্লেষণের জন্য বিশ্ববিদ্যালয় ওয়েব ইঞ্জিনিয়ারিং ল্যাব প্রজেক্ট।',
    viewElections: 'নির্বাচন দেখুন',
    howVotingWorks: 'ভোটিং পদ্ধতি',
    liveElectionHub: 'লাইভ নির্বাচন কেন্দ্র',
    liveElectionDescription: 'বর্তমানে চলমান নির্বাচন, ভোট সংখ্যা, এগিয়ে থাকা প্রার্থী, সময়, টার্নআউট এবং আসনভিত্তিক অগ্রগতি।',
    runningNow: 'এখন চলছে',
    totalVotes: 'মোট ভোট',
    leading: 'এগিয়ে আছে',
    timeLeft: 'বাকি সময়',
    seat: 'আসন',
    liveChart: 'লাইভ চার্ট',
    coreFeatures: 'মূল ফিচার',
    coreFeaturesDescription: 'ল্যাব ডেমোর জন্য সহজ, নিরাপদ এবং যাচাইযোগ্য ফিচার।',
    votingProcess: 'ভোটিং প্রক্রিয়া',
    importantNotice: 'গুরুত্বপূর্ণ নোটিশ',
    noticeText: 'এটি একটি একাডেমিক প্রজেক্ট। বাস্তব সরকারি নির্বাচনের জন্য সার্টিফাইড পরিচয় যাচাই, নিরাপত্তা অডিট, আইনি অনুমোদন এবং স্বাধীন অবকাঠামো পর্যালোচনা প্রয়োজন।',
    securityAssurance: 'নিরাপত্তা নিশ্চয়তা',
    securityAssuranceText: 'ব্যালটে নাম, ইমেইল, ফোন বা NID সরাসরি সংরক্ষণ করা হয় না। ভোট ব্লকে SHA-256 হ্যাশ এবং আগের ব্লকের রেফারেন্স থাকে, তাই অডিটে পরিবর্তন ধরা যায়।',
    voterRegistration: 'ভোটার রেজিস্ট্রেশন',
    registrationDescription: 'ইমেইল, ফোন এবং অনুমোদিত ১০ বা ১৬ ডিজিটের ভোটার/NID নম্বর দিয়ে একটি নিরাপদ ভোটার অ্যাকাউন্ট তৈরি করুন।',
    visitorMessage: 'ভিজিটররা সরাসরি পাবলিক প্রজেক্ট পেজ দেখতে পারবে। ভোটার ও অ্যাডমিনকে সুরক্ষিত কাজের জন্য লগইন করতে হবে।',
    emailAddress: 'ইমেইল ঠিকানা',
    password: 'পাসওয়ার্ড',
    forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
    createVoterAccount: 'ভোটার অ্যাকাউন্ট তৈরি করুন',
    adminLoginOption: 'অ্যাডমিন লগইন অপশন',
    securityMessage: 'নিরাপত্তা বার্তা',
    approvalWarning: 'অ্যাডমিন অনুমোদনের অপেক্ষায় থাকা বা সাসপেন্ডেড অ্যাকাউন্ট লগইনের পরেও ভোট দিতে পারবে না।',
    account: 'অ্যাকাউন্ট',
    voterInformation: 'ভোটার তথ্য',
    review: 'রিভিউ',
    fullName: 'পূর্ণ নাম',
    confirmPassword: 'পাসওয়ার্ড নিশ্চিত করুন',
    voterNidNumber: 'ভোটার/NID নম্বর',
    dateOfBirth: 'জন্ম তারিখ',
    phoneNumber: 'ফোন নম্বর',
    region: 'অঞ্চল',
    back: 'পিছনে',
    continue: 'চালিয়ে যান',
    submitRegistration: 'রেজিস্ট্রেশন জমা দিন',
  },
};

export const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('appLanguage') || 'en');

  useEffect(() => {
    localStorage.setItem('appLanguage', language);
    document.documentElement.lang = language === 'bn' ? 'bn' : 'en';
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key) => translations[language]?.[key] ?? translations.en[key] ?? key,
    }),
    [language],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}
