import { createContext, useEffect, useMemo, useState } from 'react';

const translations = {
  en: {
    home: 'Home',
    elections: 'Elections',
    howItWorks: 'How It Works',
    security: 'Security',
    voteVerification: 'Vote Verification',
    help: 'Help',
    login: 'Login',
    voterLogin: 'Voter Login',
    adminLogin: 'Admin Login',
    register: 'Register',
    profile: 'Profile',
    siteName: 'Secure Voting System',
    siteSubtitle: 'Secure, Transparent and Verifiable Voting',
    portalEyebrow: 'National Digital Election Portal',
    projectTitle: 'Secure Digital Voting System',
    heroSubtitle: 'A citizen-focused online voting portal for verified voter access, anonymous ballots, transparent counting, and tamper-evident election records.',
    viewElections: 'View Elections',
    howVotingWorks: 'How Voting Works',
    liveElectionHub: 'Live Election Monitoring',
    liveElectionDescription: 'Currently running elections, vote counts, leading candidates, timing, turnout, and seat-wise progress.',
    runningNow: 'Running now',
    totalVotes: 'Total votes',
    leading: 'Leading',
    timeLeft: 'Time left',
    seat: 'Seat',
    liveChart: 'Live chart',
    votes: 'votes',
    coreFeatures: 'Core Services',
    coreFeaturesDescription: 'Digital voting services designed for trust, clarity, and election transparency.',
    secureRegistration: 'Verified Voter Registration',
    emailVerification: 'Email and 2FA Verification',
    anonymousVoting: 'Anonymous Ballot',
    oneVoterOneVote: 'One Voter, One Vote',
    blockchainVerification: 'Blockchain Audit Trail',
    realTimeResults: 'Real-Time Results',
    fraudDetection: 'Fraud Detection',
    votingProcess: 'Voting Process',
    processRegister: 'Register',
    processVerify: 'Verify Identity',
    processApproval: 'Approval Check',
    processElection: 'Select Election',
    processVote: 'Cast Vote',
    processReceipt: 'Verify Receipt',
    importantNotice: 'Public Notice',
    noticeText: 'Only verified and approved voters can cast a vote. Public visitors can view election information, live aggregate counts, and receipt verification without seeing voter identity.',
    securityAssurance: 'Security Assurance',
    securityAssuranceText: 'Ballots do not store name, email, phone, or NID directly. Vote blocks use SHA-256 hashes and previous block references so tampering can be detected during audit verification.',
    publicInfo: 'Citizen Information',
    publicInfoText: 'Voters can register with an approved NID, sign in securely, view eligible elections, cast one vote, and verify the receipt later.',
    voterRegistration: 'Voter Registration',
    registrationDescription: 'Create one secure voter account using email, phone, and an approved 10 or 16 digit voter/NID number.',
    visitorMessage: 'Visitors can read public election information directly. Voters and admins must sign in for protected actions.',
    emailAddress: 'Email address',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    createVoterAccount: 'Create voter account',
    adminLoginOption: 'Admin login option',
    securityMessage: 'Security message',
    approvalWarning: 'Accounts waiting for approval or suspended by admin cannot vote even after login.',
    account: 'Account',
    voterInformation: 'Voter Information',
    review: 'Review',
    fullName: 'Full name',
    confirmPassword: 'Confirm password',
    voterNidNumber: 'Voter/NID number',
    dateOfBirth: 'Date of birth',
    phoneNumber: 'Phone number',
    region: 'Region',
    back: 'Back',
    continue: 'Continue',
    submitRegistration: 'Submit registration',
    checking: 'Checking...',
    creatingAccount: 'Creating account...',
    termsRequired: 'You must accept the secure voting terms.',
    registrationConsent: 'I understand this account is for verified voting access and voting permission requires identity verification and admin approval.',
    footerAbout: 'Election Portal',
    footerQuick: 'Quick Links',
    footerHelp: 'Support',
    footerSecurity: 'Security',
    footerNote: 'Secure Digital Voting System for verified voters, transparent counting, and public audit confidence.',
    overview: 'Overview',
    privacy: 'Privacy',
    terms: 'Terms',
    accessibility: 'Accessibility',
    active: 'Active',
    pending: 'Pending',
    approved: 'Approved',
    suspended: 'Suspended',
    rejected: 'Rejected',
    northRegion: 'North Region',
    southRegion: 'South Region',
    centralRegion: 'Central Region',
    departmentClubElection: 'Department Club Election',
    studentCouncilElection: 'Student Council Election 2026',
    libraryCommitteePoll: 'Library Committee Poll',
    candidateC: 'Candidate C',
    candidateD: 'Candidate D',
    candidateE: 'Candidate E',
    aboutEyebrow: 'Overview',
    aboutTitle: 'Citizen-focused secure digital voting',
    aboutDescription: 'This portal combines verified registration, protected voting, anonymous ballots, live aggregate counting, and audit verification.',
    purpose: 'Purpose',
    purposeText: 'The system gives voters a clear path to register, verify identity, view elections, cast a secure ballot, and verify a receipt.',
    safeguards: 'Safeguards',
    safeguardsText: 'The voting workflow separates public information, voter identity, anonymous ballots, admin approval, and blockchain-style audit records.',
    processEyebrow: 'Process',
    processTitle: 'How secure voting works',
    processDescription: 'The voter experience stays simple while identity checks, eligibility, duplicate prevention, and audit records run on the server side.',
    securityEyebrow: 'Security',
    securityTitle: 'Security controls and audit design',
    securityDescription: 'The portal uses layered controls for account access, voter approval, anonymous ballots, receipt checks, fraud monitoring, and blockchain-style verification.',
  },
  bn: {
    home: 'হোম',
    elections: 'নির্বাচন',
    howItWorks: 'কিভাবে কাজ করে',
    security: 'নিরাপত্তা',
    voteVerification: 'ভোট যাচাই',
    help: 'সহায়তা',
    login: 'লগইন',
    voterLogin: 'ভোটার লগইন',
    adminLogin: 'অ্যাডমিন লগইন',
    register: 'নিবন্ধন',
    profile: 'প্রোফাইল',
    siteName: 'নিরাপদ ভোটিং সিস্টেম',
    siteSubtitle: 'নিরাপদ, স্বচ্ছ ও যাচাইযোগ্য ভোটিং',
    portalEyebrow: 'জাতীয় ডিজিটাল নির্বাচন পোর্টাল',
    projectTitle: 'নিরাপদ ডিজিটাল ভোটিং সিস্টেম',
    heroSubtitle: 'যাচাইকৃত ভোটার প্রবেশাধিকার, গোপন ব্যালট, স্বচ্ছ গণনা এবং পরিবর্তন-সনাক্তযোগ্য নির্বাচন রেকর্ডের জন্য নাগরিক-কেন্দ্রিক অনলাইন ভোটিং পোর্টাল।',
    viewElections: 'নির্বাচন দেখুন',
    howVotingWorks: 'ভোটিং পদ্ধতি',
    liveElectionHub: 'লাইভ নির্বাচন পর্যবেক্ষণ',
    liveElectionDescription: 'চলমান নির্বাচন, ভোট সংখ্যা, এগিয়ে থাকা প্রার্থী, সময়, টার্নআউট এবং আসনভিত্তিক অগ্রগতি।',
    runningNow: 'এখন চলছে',
    totalVotes: 'মোট ভোট',
    leading: 'এগিয়ে আছে',
    timeLeft: 'বাকি সময়',
    seat: 'আসন',
    liveChart: 'লাইভ চার্ট',
    votes: 'ভোট',
    coreFeatures: 'মূল সেবা',
    coreFeaturesDescription: 'আস্থা, স্বচ্ছতা এবং নির্বাচন পর্যবেক্ষণের জন্য তৈরি ডিজিটাল ভোটিং সেবা।',
    secureRegistration: 'যাচাইকৃত ভোটার নিবন্ধন',
    emailVerification: 'ইমেইল ও ২এফএ যাচাই',
    anonymousVoting: 'গোপন ব্যালট',
    oneVoterOneVote: 'এক ভোটার, এক ভোট',
    blockchainVerification: 'ব্লকচেইন অডিট ট্রেইল',
    realTimeResults: 'রিয়েল-টাইম ফলাফল',
    fraudDetection: 'জালিয়াতি শনাক্তকরণ',
    votingProcess: 'ভোটিং প্রক্রিয়া',
    processRegister: 'নিবন্ধন',
    processVerify: 'পরিচয় যাচাই',
    processApproval: 'অনুমোদন যাচাই',
    processElection: 'নির্বাচন নির্বাচন',
    processVote: 'ভোট প্রদান',
    processReceipt: 'রসিদ যাচাই',
    importantNotice: 'সর্বসাধারণের নোটিশ',
    noticeText: 'শুধুমাত্র যাচাইকৃত ও অনুমোদিত ভোটার ভোট দিতে পারবেন। সাধারণ দর্শনার্থীরা ভোটারের পরিচয় না দেখে নির্বাচনের তথ্য, লাইভ সামগ্রিক গণনা এবং রসিদ যাচাই দেখতে পারবেন।',
    securityAssurance: 'নিরাপত্তা নিশ্চয়তা',
    securityAssuranceText: 'ব্যালটে নাম, ইমেইল, ফোন বা NID সরাসরি সংরক্ষণ করা হয় না। ভোট ব্লকে SHA-256 হ্যাশ এবং আগের ব্লকের রেফারেন্স থাকে, তাই অডিটে পরিবর্তন শনাক্ত করা যায়।',
    publicInfo: 'নাগরিক তথ্য',
    publicInfoText: 'ভোটার অনুমোদিত NID দিয়ে নিবন্ধন, নিরাপদে লগইন, যোগ্য নির্বাচন দেখা, একবার ভোট প্রদান এবং পরে রসিদ যাচাই করতে পারবেন।',
    voterRegistration: 'ভোটার নিবন্ধন',
    registrationDescription: 'ইমেইল, ফোন এবং অনুমোদিত ১০ বা ১৬ ডিজিটের ভোটার/NID নম্বর দিয়ে একটি নিরাপদ ভোটার অ্যাকাউন্ট তৈরি করুন।',
    visitorMessage: 'দর্শনার্থীরা সরাসরি পাবলিক নির্বাচনী তথ্য দেখতে পারবেন। ভোটার ও অ্যাডমিনকে সুরক্ষিত কাজের জন্য লগইন করতে হবে।',
    emailAddress: 'ইমেইল ঠিকানা',
    password: 'পাসওয়ার্ড',
    forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
    createVoterAccount: 'ভোটার অ্যাকাউন্ট তৈরি করুন',
    adminLoginOption: 'অ্যাডমিন লগইন অপশন',
    securityMessage: 'নিরাপত্তা বার্তা',
    approvalWarning: 'অ্যাডমিন অনুমোদনের অপেক্ষায় থাকা বা সাসপেন্ডেড অ্যাকাউন্ট লগইনের পরেও ভোট দিতে পারবে না।',
    account: 'অ্যাকাউন্ট',
    voterInformation: 'ভোটার তথ্য',
    review: 'রিভিউ',
    fullName: 'পূর্ণ নাম',
    confirmPassword: 'পাসওয়ার্ড নিশ্চিত করুন',
    voterNidNumber: 'ভোটার/NID নম্বর',
    dateOfBirth: 'জন্ম তারিখ',
    phoneNumber: 'ফোন নম্বর',
    region: 'অঞ্চল',
    back: 'পিছনে',
    continue: 'চালিয়ে যান',
    submitRegistration: 'নিবন্ধন জমা দিন',
    checking: 'যাচাই হচ্ছে...',
    creatingAccount: 'অ্যাকাউন্ট তৈরি হচ্ছে...',
    termsRequired: 'নিরাপদ ভোটিং শর্তাবলি গ্রহণ করতে হবে।',
    registrationConsent: 'আমি বুঝেছি এই অ্যাকাউন্ট যাচাইকৃত ভোটিং প্রবেশাধিকারের জন্য এবং ভোট দেওয়ার অনুমতি পেতে পরিচয় যাচাই ও অ্যাডমিন অনুমোদন প্রয়োজন।',
    footerAbout: 'নির্বাচন পোর্টাল',
    footerQuick: 'দ্রুত লিংক',
    footerHelp: 'সহায়তা',
    footerSecurity: 'নিরাপত্তা',
    footerNote: 'যাচাইকৃত ভোটার, স্বচ্ছ গণনা এবং জনসাধারণের অডিট আস্থার জন্য নিরাপদ ডিজিটাল ভোটিং সিস্টেম।',
    overview: 'ওভারভিউ',
    privacy: 'গোপনীয়তা',
    terms: 'শর্তাবলি',
    accessibility: 'অ্যাক্সেসিবিলিটি',
    active: 'চলমান',
    pending: 'অপেক্ষমান',
    approved: 'অনুমোদিত',
    suspended: 'স্থগিত',
    rejected: 'বাতিল',
    northRegion: 'উত্তর অঞ্চল',
    southRegion: 'দক্ষিণ অঞ্চল',
    centralRegion: 'কেন্দ্রীয় অঞ্চল',
    departmentClubElection: 'বিভাগীয় ক্লাব নির্বাচন',
    studentCouncilElection: 'স্টুডেন্ট কাউন্সিল নির্বাচন ২০২৬',
    libraryCommitteePoll: 'লাইব্রেরি কমিটি ভোট',
    candidateC: 'প্রার্থী গ',
    candidateD: 'প্রার্থী ঘ',
    candidateE: 'প্রার্থী ঙ',
    aboutEyebrow: 'ওভারভিউ',
    aboutTitle: 'নাগরিক-কেন্দ্রিক নিরাপদ ডিজিটাল ভোটিং',
    aboutDescription: 'এই পোর্টাল যাচাইকৃত নিবন্ধন, সুরক্ষিত ভোটিং, গোপন ব্যালট, লাইভ সামগ্রিক গণনা এবং অডিট যাচাই একসাথে করে।',
    purpose: 'উদ্দেশ্য',
    purposeText: 'সিস্টেমটি ভোটারকে নিবন্ধন, পরিচয় যাচাই, নির্বাচন দেখা, নিরাপদ ব্যালট প্রদান এবং রসিদ যাচাইয়ের পরিষ্কার পথ দেয়।',
    safeguards: 'সুরক্ষা ব্যবস্থা',
    safeguardsText: 'ভোটিং প্রক্রিয়ায় পাবলিক তথ্য, ভোটার পরিচয়, গোপন ব্যালট, অ্যাডমিন অনুমোদন এবং ব্লকচেইন-স্টাইল অডিট রেকর্ড আলাদা রাখা হয়।',
    processEyebrow: 'প্রক্রিয়া',
    processTitle: 'নিরাপদ ভোটিং কিভাবে কাজ করে',
    processDescription: 'ভোটারের অভিজ্ঞতা সহজ থাকে, আর পরিচয় যাচাই, যোগ্যতা, ডুপ্লিকেট প্রতিরোধ এবং অডিট রেকর্ড সার্ভার সাইডে চলে।',
    securityEyebrow: 'নিরাপত্তা',
    securityTitle: 'নিরাপত্তা নিয়ন্ত্রণ ও অডিট ডিজাইন',
    securityDescription: 'পোর্টালটি অ্যাকাউন্ট প্রবেশাধিকার, ভোটার অনুমোদন, গোপন ব্যালট, রসিদ যাচাই, জালিয়াতি পর্যবেক্ষণ এবং ব্লকচেইন-স্টাইল যাচাইয়ের জন্য স্তরভিত্তিক নিয়ন্ত্রণ ব্যবহার করে।',
  },
};

export const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('appLanguage') || 'en');

  useEffect(() => {
    localStorage.setItem('appLanguage', language);
    document.documentElement.lang = language === 'bn' ? 'bn' : 'en';
    document.documentElement.dataset.language = language;
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key) => translations[language]?.[key] ?? translations.en[key] ?? key,
    }),
    [language],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}
